### ISSUE TITLE
Completion doesn't support fine-tuned models

### ISSUE THREAD

**Issue by dustinlacewell** [ceifa/openai#1]
Currently the completion API forces you to provide the engine name. However, to work with fine-tuned models you must pass the `model` parameter, but not the engine parameter.

**Comment by ceifa** [comment]
Thanks for the report! I was pretty confident we can just pass the fine-tuned model as an engine. I will test it and fix later. Feel free to open a PR too.

**Comment by dustinlacewell** [comment]
FWIW, by switching to just using axios and interacting with the API directly, I've been able to obtain fine-tuned completions by indeed passing the `model` parameter.

**Comment by el-abdel** [comment]
Hello, I opened a PR linked to this issue

**Comment by ceifa** [comment]
Fixed by #2 available on 0.0.9
